[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

[tool.coverage.run]
branch = true
source = ["."]

[tool.coverage.report]
fail_under = 85
show_missing = true
